In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

from IPython.display import display
pd.options.display.max_columns = None

In [2]:
meta = pd.read_csv('nba_playoffs_meta.csv')
meta

,team,team_short,conference,game_won,game_lose,conference_position,game_played,points_scored,points_missed,game_won_home,game_lose_home,game_won_away,game_lose_away
0,Philadelphia 76ers,PHI,EAST,54,28,3,82,9446,9094,29,12,25,16
1,Brooklyn Nets,BKN,EAST,45,37,6,82,9299,9225,23,18,22,19
2,Denver Nuggets,DEN,WEST,53,29,1,82,9479,9225,34,7,19,22
3,Boston Celtics,BOS,EAST,57,25,2,82,9668,9135,32,9,25,16
4,Milwaukee Bucks,MIL,EAST,58,24,1,82,9586,9291,32,9,26,15
5,Atlanta Hawks,ATL,EAST,41,41,7,82,9709,9684,24,17,17,24
6,Golden State Warriors,GSW,WEST,44,38,6,82,9750,9602,33,8,11,30
7,LA Lakers,LAL,WEST,43,39,7,82,9610,9561,23,18,20,21
8,LA Clippers,LAC,WEST,44,38,5,82,9315,9274,23,18,21,20
9,Minnesota Timberwolves,MIN,WEST,42,40,8,82,9471,9471,22,19,20,21
10,Miami Heat,MIA,EAST,44,38,8,82,8979,9003,27,14,17,24
11,Sacramento Kings,SAC,WEST,48,34,3,82,9897,9684,23,18,25,16
12,Memphis Grizzlies,MEM,WEST,51,31,2,82,9586,9266,35,6,16,25
13,Phoenix Suns,PHX,WEST,45,37,4,82,9315,9151,28,13,17,24
14,New York Knicks,NYK,EAST,47,35,5,82,9512,9274,23,18,24,17
15,Cleveland Cavaliers,CAV,EAST,51,31,4,82,9209,8766,31,10,20,21

In [3]:
games = pd.read_csv('nba_playoffs_games.csv')
games

,series_id,home_team,away_team,home_points,away_points,round,game,score_home,score_away
0,1,PHI,BKN,121,101,1,1,0,0
1,1,PHI,BKN,96,84,1,2,1,0
2,1,BKN,PHI,97,102,1,3,0,2
3,1,BKN,PHI,88,96,1,4,0,3
4,2,BOS,ATL,112,99,1,1,0,0
5,2,BOS,ATL,119,106,1,2,1,0
6,2,ATL,BOS,130,122,1,3,0,2
7,2,ATL,BOS,121,129,1,4,1,2
8,2,BOS,ATL,117,119,1,5,1,3
9,2,ATL,BOS,120,128,1,6,2,3
10,3,CAV,NYK,97,101,1,1,0,0
11,3,CAV,NYK,107,90,1,2,1,0
12,3,NYK,CAV,99,79,1,3,1,1
13,3,NYK,CAV,102,93,1,4,2,1
14,3,CAV,NYK,95,106,1,5,1,3
15,4,SAC,GSW,126,123,1,1,0,0
16,4,SAC,GSW,114,106,1,2,1,0
17,4,GSW,SAC,114,97,1,3,0,2
18,4,GSW,SAC,126,125,1,4,1,2
19,4,SAC,GSW,116,123,1,5,2,2
20,4,GSW,SAC,99,118,1,6,3,2
21,4,SAC,GSW,100,120,1,7,3,3
22,5,MEM,LAL,112,128,1,1,0,0
23,5,MEM,LAL,103,93,1,2,0,1
24,5,LAL,MEM,111,101,1,3,1,1
25,5,LAL,MEM,117,111,1,4,2,1
26,5,MEM,LAL,116,99,1,5,1,3
27,5,LAL,MEM,125,85,1,6,3,2
28,6,MIL,MIA,117,130,1,1,0,0
29,6,MIL,MIA,138,122,1,2,0,1
30,6,MIA,MIL,121,99,1,3,1,1
31,6,MIA,MIL,119,114,1,4,2,1
32,6,MIL,MIA,126,128,1,5,1,3
33,7,PHX,LAC,110,115,1,1,0,0
34,7,PHX,LAC,123,109,1,2,0,1
35,7,LAC,PHX,124,129,1,3,1,1
36,7,LAC,PHX,100,112,1,4,1,2
37,7,PHX,LAC,136,130,1,5,3,1
38,8,DEN,MIN,109,80,1,1,0,0
39,8,DEN,MIN,122,113,1,2,1,0
40,8,MIN,DEN,111,120,1,3,0,2
41,8,MIN,DEN,114,108,1,4,0,3
42,8,DEN,MIN,112,109,1,5,3,1

In [4]:
df = pd.merge(games, meta,
left_on='home_team', right_on='team_short')
df = df.drop(['team', 'team_short', 'conference'], axis=1)
df['home_team_win_ratio'] = df['game_won'] / df['game_played']
df['home_team_points_per_game'] = df['points_scored'] / df['game_played']
df['home_team_missed_points'] = df['points_missed'] / df['game_played']
df['home_team_home_win_ratio'] = df['game_won_home'] / (df['game_won_home'] + df['game_lose_home'])
df['home_team_away_win_ratio'] = df['game_won_away'] / (df['game_won_away'] + df['game_lose_away'])
df = df.drop(['game_won', 'game_lose', 'game_played', 'points_scored', 'points_missed', 'game_won_home', 'game_lose_home', 'game_won_away', 'game_lose_away'], axis=1)
df.columns = ['series_id', 'home_team', 'away_team', 'home_points', 'away_points', 'round', 'game', 'score_home', 'score_away', 'home_conference_position',
              'home_team_win_ratio', 'home_team_points_per_game', 'home_team_missed_points', 'home_team_home_win_ratio', 'home_team_away_win_ratio']
df = pd.merge(df, meta, left_on='away_team', right_on='team_short')
df = df.drop(['team', 'team_short', 'conference'], axis=1)
df['away_team_win_ratio'] = df['game_won'] / df['game_played']
df['away_team_points_per_game'] = df['points_scored'] / df['game_played']
df['away_team_missed_points'] = df['points_missed'] / df['game_played']
df['away_team_home_win_ratio'] = df['game_won_home'] / (df['game_won_home'] + df['game_lose_home'])
df['away_team_away_win_ratio'] = df['game_won_away'] / (df['game_won_away'] + df['game_lose_away'])
df = df.drop(['game_won', 'game_lose', 'game_played', 'points_scored', 'points_missed', 'game_won_home', 'game_lose_home', 'game_won_away', 'game_lose_away'], axis=1)

In [5]:
X = df.drop(['home_points', 'away_points'], axis=1)
y = df[['home_points', 'away_points']]
X

,series_id,home_team,away_team,round,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,PHI,BKN,1,1,0,0,3,0.658537,115.195122,110.902439,0.707317,0.609756,6,0.548780,113.402439,112.500000,0.560976,0.536585
1,1,PHI,BKN,1,2,1,0,3,0.658537,115.195122,110.902439,0.707317,0.609756,6,0.548780,113.402439,112.500000,0.560976,0.536585
2,1,BKN,PHI,1,3,0,2,6,0.548780,113.402439,112.500000,0.560976,0.536585,3,0.658537,115.195122,110.902439,0.707317,0.609756
3,1,BKN,PHI,1,4,0,3,6,0.548780,113.402439,112.500000,0.560976,0.536585,3,0.658537,115.195122,110.902439,0.707317,0.609756
4,2,BOS,ATL,1,1,0,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,7,0.500000,118.402439,118.097561,0.585366,0.414634
5,2,BOS,ATL,1,2,1,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,7,0.500000,118.402439,118.097561,0.585366,0.414634
6,2,BOS,ATL,1,5,1,3,2,0.695122,117.902439,111.402439,0.780488,0.609756,7,0.500000,118.402439,118.097561,0.585366,0.414634
7,2,ATL,BOS,1,3,0,2,7,0.500000,118.402439,118.097561,0.585366,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756
8,2,ATL,BOS,1,4,1,2,7,0.500000,118.402439,118.097561,0.585366,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756
9,2,ATL,BOS,1,6,2,3,7,0.500000,118.402439,118.097561,0.585366,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756
10,3,CAV,NYK,1,1,0,0,4,0.621951,112.304878,106.902439,0.756098,0.487805,5,0.573171,116.000000,113.097561,0.560976,0.585366
11,3,CAV,NYK,1,2,1,0,4,0.621951,112.304878,106.902439,0.756098,0.487805,5,0.573171,116.000000,113.097561,0.560976,0.585366
12,3,CAV,NYK,1,5,1,3,4,0.621951,112.304878,106.902439,0.756098,0.487805,5,0.573171,116.000000,113.097561,0.560976,0.585366
13,3,NYK,CAV,1,3,1,1,5,0.573171,116.000000,113.097561,0.560976,0.585366,4,0.621951,112.304878,106.902439,0.756098,0.487805
14,3,NYK,CAV,1,4,2,1,5,0.573171,116.000000,113.097561,0.560976,0.585366,4,0.621951,112.304878,106.902439,0.756098,0.487805
15,4,SAC,GSW,1,1,0,0,3,0.585366,120.695122,118.097561,0.560976,0.609756,6,0.536585,118.902439,117.097561,0.804878,0.268293
16,4,SAC,GSW,1,2,1,0,3,0.585366,120.695122,118.097561,0.560976,0.609756,6,0.536585,118.902439,117.097561,0.804878,0.268293
17,4,SAC,GSW,1,5,2,2,3,0.585366,120.695122,118.097561,0.560976,0.609756,6,0.536585,118.902439,117.097561,0.804878,0.268293
18,4,SAC,GSW,1,7,3,3,3,0.585366,120.695122,118.097561,0.560976,0.609756,6,0.536585,118.902439,117.097561,0.804878,0.268293
19,4,GSW,SAC,1,3,0,2,6,0.536585,118.902439,117.097561,0.804878,0.268293,3,0.585366,120.695122,118.097561,0.560976,0.609756
20,4,GSW,SAC,1,4,1,2,6,0.536585,118.902439,117.097561,0.804878,0.268293,3,0.585366,120.695122,118.097561,0.560976,0.609756
21,4,GSW,SAC,1,6,3,2,6,0.536585,118.902439,117.097561,0.804878,0.268293,3,0.585366,120.695122,118.097561,0.560976,0.609756
22,5,MEM,LAL,1,1,0,0,2,0.621951,116.902439,113.000000,0.853659,0.390244,7,0.524390,117.195122,116.597561,0.560976,0.487805
23,5,MEM,LAL,1,2,0,1,2,0.621951,116.902439,113.000000,0.853659,0.390244,7,0.524390,117.195122,116.597561,0.560976,0.487805
24,5,MEM,LAL,1,5,1,3,2,0.621951,116.902439,113.000000,0.853659,0.390244,7,0.524390,117.195122,116.597561,0.560976,0.487805
25,5,LAL,MEM,1,3,1,1,7,0.524390,117.195122,116.597561,0.560976,0.487805,2,0.621951,116.902439,113.000000,0.853659,0.390244
26,5,LAL,MEM,1,4,2,1,7,0.524390,117.195122,116.597561,0.560976,0.487805,2,0.621951,116.902439,113.000000,0.853659,0.390244
27,5,LAL,MEM,1,6,3,2,7,0.524390,117.195122,116.597561,0.560976,0.487805,2,0.621951,116.902439,113.000000,0.853659,0.390244
28,6,MIL,MIA,1,1,0,0,1,0.707317,116.902439,113.304878,0.780488,0.634146,8,0.536585,109.500000,109.792683,0.658537,0.414634
29,6,MIL,MIA,1,2,0,1,1,0.707317,116.902439,113.304878,0.780488,0.634146,8,0.536585,109.500000,109.792683,0.658537,0.414634
30,6,MIL,MIA,1,5,1,3,1,0.707317,116.902439,113.304878,0.780488,0.634146,8,0.536585,109.500000,109.792683,0.658537,0.414634
31,6,MIA,MIL,1,3,1,1,8,0.536585,109.500000,109.792683,0.658537,0.414634,1,0.707317,116.902439,113.304878,0.780488,0.634146
32,6,MIA,MIL,1,4,2,1,8,0.536585,109.500000,109.792683,0.658537,0.414634,1,0.707317,116.902439,113.304878,0.780488,0.634146
33,7,PHX,LAC,1,1,0,0,4,0.548780,113.597561,111.597561,0.682927,0.414634,5,0.536585,113.597561,113.097561,0.560976,0.512195
34,7,PHX,LAC,1,2,0,1,4,0.548780,113.597561,111.597561,0.682927,0.414634,5,0.536585,113.597561,113.097561,0.560976,0.512195
35,7,PHX,LAC,1,5,3,1,4,0.548780,113.597561,111.597561,0.682927,0.414634,5,0.536585,113.597561,113.097561,0.560976,0.512195
36,7,LAC,PHX,1,3,1,1,5,0.536585,113.597561,113.097561,0.560976,0.512195,4,0.548780,113.597561,111.597561,0.682927,0.414634
37,7,LAC,PHX,1,4,1,2,5,0.536585,113.597561,113.097561,0.560976,0.512195,4,0.548780,113.597561,111.597561,0.682927,0.414634
38,8,DEN,MIN,1,1,0,0,1,0.646341,115.597561,112.500000,0.829268,0.463415,8,0.512195,115.500000,115.500000,0.536585,0.487805
39,8,DEN,MIN,1,2,1,0,1,0.646341,115.597561,112.500000,0.829268,0.463415,8,0.512195,115.500000,115.500000,0.536585,0.487805
40,8,DEN,MIN,1,5,3,1,1,0.646341,115.597561,112.500000,0.829268,0.463415,8,0.512195,115.500000,115.500000,0.536585,0.487805
41,8,MIN,DEN,1,3,0,2,8,0.512195,115.500000,115.500000,0.536585,0.487805,1,0.646341,115.597561,112.500000,0.829268,0.463415
42,8,MIN,DEN,1,4,0,3,8,0.512195,115.500000,115.500000,0.536585,0.487805,1,0.646341,115.597561,112.500000,0.829268,0.463415

In [6]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

In [7]:
Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("neg_root_mean_squared_error Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("neg_root_mean_squared_error Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

neg_root_mean_squared_error Home: -17.84 (+/- 13.86)
neg_root_mean_squared_error Away: -24.97 (+/- 11.28)

In [8]:
#################
#################
#Boston - Philadelphia
#################
#################

In [9]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,3,0.658537,115.195122,110.902439,0.707317,0.609756

In [10]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHILADELPHIA points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  117
PHILADELPHIA points:  101

In [11]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHI'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -16.99 (+/- 10.66)
Score Away: -21.72 (+/- 12.66)

In [12]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,3,0.658537,115.195122,110.902439,0.707317,0.609756

In [13]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHILADELPHIA points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  117
PHILADELPHIA points:  90

In [14]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHI'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -18.35 (+/- 8.77)
Score Away: -20.78 (+/- 12.57)

In [15]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,0,2,3,0.658537,115.195122,110.902439,0.707317,0.609756,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [16]:
print('PHILADELPHIA points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

PHILADELPHIA points:  130
BOSTON points:  99

In [17]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHI'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -14.85 (+/- 12.45)
Score Away: -20.54 (+/- 14.24)

In [18]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,1,2,3,0.658537,115.195122,110.902439,0.707317,0.609756,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [19]:
print('PHILADELPHIA points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

PHILADELPHIA points:  126
BOSTON points:  114

In [20]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHI'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -15.33 (+/- 15.44)
Score Away: -19.71 (+/- 12.71)

In [21]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,2,2,2,0.695122,117.902439,111.402439,0.780488,0.609756,3,0.658537,115.195122,110.902439,0.707317,0.609756

In [22]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHILADELPHIA points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  126
PHILADELPHIA points:  106

In [23]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHI'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.51 (+/- 14.66)
Score Away: -16.98 (+/- 16.16)

In [24]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 6}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,6,2,3,3,0.658537,115.195122,110.902439,0.707317,0.609756,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [25]:
print('PHILADELPHIA points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

PHILADELPHIA points:  126
BOSTON points:  114

In [26]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHI'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.98 (+/- 13.95)
Score Away: -15.95 (+/- 14.48)

In [27]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 7}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHI']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHI']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHI']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHI']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,7,3,3,2,0.695122,117.902439,111.402439,0.780488,0.609756,3,0.658537,115.195122,110.902439,0.707317,0.609756

In [28]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHILADELPHIA points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  126
PHILADELPHIA points:  106

In [29]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHI'
X = pd.concat([X, Xtr])

X_semi = X.tail(7)
y_semi = y.tail(7)

In [30]:
###### BOSTON 4 - 3 PHILADELPHIA

In [31]:
#################
#################
#New York - Miami
#################
#################

In [32]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,5,0.573171,116.0,113.097561,0.560976,0.585366,8,0.536585,109.5,109.792683,0.658537,0.414634

In [33]:
print('NEW YORK points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

NEW YORK points:  121
MIAMI points:  101

In [34]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'NYK'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -14.49 (+/- 10.50)
Score Away: -15.84 (+/- 14.39)

In [35]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,5,0.573171,116.0,113.097561,0.560976,0.585366,8,0.536585,109.5,109.792683,0.658537,0.414634

In [36]:
print('NEW YORK points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

NEW YORK points:  138
MIAMI points:  84

In [37]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'NYK'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -15.75 (+/- 13.49)
Score Away: -18.50 (+/- 18.47)

In [38]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,0,2,8,0.536585,109.5,109.792683,0.658537,0.414634,5,0.573171,116.0,113.097561,0.560976,0.585366

In [39]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('NEW YORK points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  121
NEW YORK points:  102

In [40]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'NYK'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -15.69 (+/- 9.29)
Score Away: -18.58 (+/- 16.18)

In [41]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,1,2,8,0.536585,109.5,109.792683,0.658537,0.414634,5,0.573171,116.0,113.097561,0.560976,0.585366

In [42]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('NEW YORK points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  119
NEW YORK points:  106

In [43]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'NYK'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -16.16 (+/- 9.81)
Score Away: -14.89 (+/- 15.70)

In [44]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,2,2,5,0.573171,116.0,113.097561,0.560976,0.585366,8,0.536585,109.5,109.792683,0.658537,0.414634

In [45]:
print('NEW YORK points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

NEW YORK points:  126
MIAMI points:  93

In [46]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'NYK'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -16.43 (+/- 9.31)
Score Away: -12.91 (+/- 14.09)

In [47]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 6}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,6,2,3,8,0.536585,109.5,109.792683,0.658537,0.414634,5,0.573171,116.0,113.097561,0.560976,0.585366

In [48]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('NEW YORK points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  119
NEW YORK points:  106

In [49]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'NYK'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.34 (+/- 9.54)
Score Away: -13.50 (+/- 11.75)

In [50]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 7}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'NYK']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'NYK']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'NYK']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'NYK']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,7,3,3,5,0.573171,116.0,113.097561,0.560976,0.585366,8,0.536585,109.5,109.792683,0.658537,0.414634

In [51]:
print('NEW YORK points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

NEW YORK points:  126
MIAMI points:  93

In [52]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'NYK'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

X_semi1 = X.tail(7)
y_semi1 = y.tail(7)

In [53]:
###### MIAMI 4 - 3 NEW YORK

In [54]:
#################
#################
#Golden State - Los Angeles
#################
#################

In [55]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,6,0.536585,118.902439,117.097561,0.804878,0.268293,7,0.52439,117.195122,116.597561,0.560976,0.487805

In [56]:
print('GOLDEN STATE points: ', int(model_home.predict(Xtr)[0]))
print('LAKERS points: ', int(model_away.predict(Xtr)[0]))

GOLDEN STATE points:  112
LAKERS points:  97

In [57]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'GSW'
Xtr['away_team'] = 'LAL'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -12.61 (+/- 12.45)
Score Away: -14.55 (+/- 13.37)

In [58]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,6,0.536585,118.902439,117.097561,0.804878,0.268293,7,0.52439,117.195122,116.597561,0.560976,0.487805

In [59]:
print('GOLDEN STATE points: ', int(model_home.predict(Xtr)[0]))
print('LAKERS points: ', int(model_away.predict(Xtr)[0]))

GOLDEN STATE points:  122
LAKERS points:  97

In [60]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'GSW'
Xtr['away_team'] = 'LAL'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -12.68 (+/- 10.79)
Score Away: -14.27 (+/- 12.70)

In [61]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,0,2,7,0.52439,117.195122,116.597561,0.560976,0.487805,6,0.536585,118.902439,117.097561,0.804878,0.268293

In [62]:
print('LAKERS points: ', int(model_home.predict(Xtr)[0]))
print('GOLDEN STATE points: ', int(model_away.predict(Xtr)[0]))

LAKERS points:  126
GOLDEN STATE points:  97

In [63]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'LAL'
Xtr['away_team'] = 'GSW'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.52 (+/- 11.94)
Score Away: -14.76 (+/- 11.31)

In [64]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,1,2,7,0.52439,117.195122,116.597561,0.560976,0.487805,6,0.536585,118.902439,117.097561,0.804878,0.268293

In [65]:
print('LAKERS points: ', int(model_home.predict(Xtr)[0]))
print('GOLDEN STATE points: ', int(model_away.predict(Xtr)[0]))

LAKERS points:  111
GOLDEN STATE points:  125

In [66]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'LAL'
Xtr['away_team'] = 'GSW'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -14.83 (+/- 13.51)
Score Away: -14.79 (+/- 14.70)

In [67]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,3,1,6,0.536585,118.902439,117.097561,0.804878,0.268293,7,0.52439,117.195122,116.597561,0.560976,0.487805

In [68]:
print('GOLDEN STATE points: ', int(model_home.predict(Xtr)[0]))
print('LAKERS points: ', int(model_away.predict(Xtr)[0]))

GOLDEN STATE points:  116
LAKERS points:  111

In [69]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'GSW'
Xtr['away_team'] = 'LAL'
X = pd.concat([X, Xtr])

X_semi2 = X.tail(5)
y_semi2 = y.tail(5)

In [70]:
###### GOLDEN STATE 4 - 1 LAKERS

In [71]:
#################
#################
#Denver - Phinix
#################
#################

In [72]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,1,0.646341,115.597561,112.5,0.829268,0.463415,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [73]:
print('DENVER points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

DENVER points:  109
PHINIX points:  115

In [74]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'DEN'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.88 (+/- 11.83)
Score Away: -15.59 (+/- 17.22)

In [75]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,0,1,1,0.646341,115.597561,112.5,0.829268,0.463415,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [76]:
print('DENVER points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

DENVER points:  103
PHINIX points:  109

In [77]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'DEN'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.13 (+/- 12.74)
Score Away: -17.70 (+/- 12.47)

In [78]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,2,0,4,0.54878,113.597561,111.597561,0.682927,0.414634,1,0.646341,115.597561,112.5,0.829268,0.463415

In [79]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('DENVER points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  121
DENVER points:  90

In [80]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'DEN'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.31 (+/- 10.59)
Score Away: -14.16 (+/- 14.57)

In [81]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,3,0,4,0.54878,113.597561,111.597561,0.682927,0.414634,1,0.646341,115.597561,112.5,0.829268,0.463415

In [82]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('DENVER points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  136
DENVER points:  114

In [83]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHX'
Xtr['away_team'] = 'DEN'
X = pd.concat([X, Xtr])

X_semi3 = X.tail(4)
y_semi3 = y.tail(4)

In [84]:
###### PHINIX 4 - 0 DENVER

In [85]:
#################
#################
#Boston - Miami
#################
#################

In [86]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,8,0.536585,109.5,109.792683,0.658537,0.414634

In [87]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  117
MIAMI points:  101

In [88]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.15 (+/- 11.07)
Score Away: -12.98 (+/- 16.42)

In [89]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,8,0.536585,109.5,109.792683,0.658537,0.414634

In [90]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  138
MIAMI points:  84

In [91]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -10.22 (+/- 8.05)
Score Away: -13.45 (+/- 16.20)

In [92]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,0,2,8,0.536585,109.5,109.792683,0.658537,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [93]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  130
BOSTON points:  99

In [94]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.74 (+/- 9.95)
Score Away: -13.54 (+/- 15.51)

In [95]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,1,2,8,0.536585,109.5,109.792683,0.658537,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [96]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  121
BOSTON points:  114

In [97]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.78 (+/- 9.16)
Score Away: -14.63 (+/- 15.32)

In [98]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,2,2,2,0.695122,117.902439,111.402439,0.780488,0.609756,8,0.536585,109.5,109.792683,0.658537,0.414634

In [99]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  126
MIAMI points:  93

In [100]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.93 (+/- 14.00)
Score Away: -11.76 (+/- 15.90)

In [101]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 6}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,6,2,3,8,0.536585,109.5,109.792683,0.658537,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [102]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  120
BOSTON points:  114

In [103]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.75 (+/- 12.02)
Score Away: -13.02 (+/- 12.74)

In [104]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 7}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,7,3,3,2,0.695122,117.902439,111.402439,0.780488,0.609756,8,0.536585,109.5,109.792683,0.658537,0.414634

In [105]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  126
MIAMI points:  93

In [106]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

X_semi4 = X.tail(7)
y_semi4 = y.tail(7)

In [107]:
###### BOSTON 4 - 3 MIAMI

In [108]:
#################
#################
#Phinix - Golden State
#################
#################

In [109]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,4,0.54878,113.597561,111.597561,0.682927,0.414634,6,0.536585,118.902439,117.097561,0.804878,0.268293

In [110]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('GOLDEN STATE points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  110
GOLDEN STATE points:  80

In [111]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHX'
Xtr['away_team'] = 'GSW'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -10.76 (+/- 10.53)
Score Away: -14.04 (+/- 16.15)

In [112]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,4,0.54878,113.597561,111.597561,0.682927,0.414634,6,0.536585,118.902439,117.097561,0.804878,0.268293

In [113]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('GOLDEN STATE points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  122
GOLDEN STATE points:  80

In [114]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHX'
Xtr['away_team'] = 'GSW'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -12.11 (+/- 7.61)
Score Away: -15.47 (+/- 15.29)

In [115]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,0,2,6,0.536585,118.902439,117.097561,0.804878,0.268293,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [116]:
print('GOLDEN STATE points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

GOLDEN STATE points:  114
PHINIX points:  122

In [117]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'GSW'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.42 (+/- 7.41)
Score Away: -15.13 (+/- 16.91)

In [118]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'GSW']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'GSW']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'GSW']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'GSW']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,0,3,6,0.536585,118.902439,117.097561,0.804878,0.268293,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [119]:
print('GOLDEN STATE points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

GOLDEN STATE points:  114
PHINIX points:  122

In [120]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

X_semi5 = X.tail(4)
y_semi5 = y.tail(4)

In [121]:
###### PHINIX 4 - 0 GOLDEN STATE

In [122]:
#################
#################
#Phinix - Boston
#################
#################

In [123]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [124]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  117
PHINIX points:  115

In [125]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.08 (+/- 9.03)
Score Away: -15.03 (+/- 16.10)

In [126]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,2,0.695122,117.902439,111.402439,0.780488,0.609756,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [127]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  117
PHINIX points:  115

In [128]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.11 (+/- 9.15)
Score Away: -15.30 (+/- 15.65)

In [129]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,0,2,4,0.54878,113.597561,111.597561,0.682927,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [130]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  130
BOSTON points:  99

In [131]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHX'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -13.70 (+/- 10.13)
Score Away: -14.81 (+/- 15.78)

In [132]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,1,2,4,0.54878,113.597561,111.597561,0.682927,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [133]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  121
BOSTON points:  114

In [134]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHX'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -12.09 (+/- 9.07)
Score Away: -14.57 (+/- 16.27)

In [135]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,2,2,2,0.695122,117.902439,111.402439,0.780488,0.609756,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [136]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  126
PHINIX points:  112

In [137]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'PHX'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.64 (+/- 13.37)
Score Away: -14.10 (+/- 15.67)

In [138]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 6}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,6,2,3,4,0.54878,113.597561,111.597561,0.682927,0.414634,2,0.695122,117.902439,111.402439,0.780488,0.609756

In [139]:
print('PHINIX points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

PHINIX points:  120
BOSTON points:  114

In [140]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'PHX'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -11.60 (+/- 12.20)
Score Away: -14.31 (+/- 16.61)

In [141]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 7}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'PHX']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'PHX']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'PHX']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'PHX']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,7,3,3,2,0.695122,117.902439,111.402439,0.780488,0.609756,4,0.54878,113.597561,111.597561,0.682927,0.414634

In [142]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('PHINIX points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  126
PHINIX points:  130

In [143]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

X_semi6 = X.tail(7)
y_semi6 = y.tail(7)

In [ ]:
#####Phinix won 4 3 in Finals